---
alertmanager:
  enabled: false

prometheus:
  prometheusSpec:
    service:
      type: NodePort
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: "managed-csi"
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi

grafana:
  enabled: true
  service:
    type: NodePort
  adminUser: admin
  adminPassword: admin123

nodeExporter:
  service:
    type: NodePort

kubeStateMetrics:
  enabled: true
  service:
    type: NodePort

additionalScrapeConfigs:
  - job_name: node-exporter
    static_configs:
      - targets:
          - node-exporter:9100
  - job_name: kube-state-metrics
    static_configs:
      - targets:
          - kube-state-metrics:8080
